# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KRSTI1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1476, 631)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 501, 591))
        self.groupBox.setObjectName("groupBox")
        self.radio_id4 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id4.setGeometry(QtCore.QRect(20, 31, 71, 23))
        self.radio_id4.setObjectName("radio_id4")
        self.radio_id5 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id5.setGeometry(QtCore.QRect(20, 71, 71, 23))
        self.radio_id5.setObjectName("radio_id5")
        self.radio_id6 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id6.setGeometry(QtCore.QRect(20, 111, 71, 23))
        self.radio_id6.setObjectName("radio_id6")
        self.radio_id7 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id7.setGeometry(QtCore.QRect(20, 151, 71, 23))
        self.radio_id7.setObjectName("radio_id7")
        self.radio_id8 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id8.setGeometry(QtCore.QRect(20, 190, 71, 23))
        self.radio_id8.setObjectName("radio_id8")
        self.radio_id9 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id9.setGeometry(QtCore.QRect(20, 230, 71, 23))
        self.radio_id9.setObjectName("radio_id9")
        self.radio_id10 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id10.setGeometry(QtCore.QRect(20, 269, 71, 23))
        self.radio_id10.setObjectName("radio_id10")
        self.radio_id11 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id11.setGeometry(QtCore.QRect(20, 309, 71, 23))
        self.radio_id11.setObjectName("radio_id11")
        self.radio_id12 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id12.setGeometry(QtCore.QRect(20, 350, 71, 23))
        self.radio_id12.setObjectName("radio_id12")
        self.set_id8 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id8.setGeometry(QtCore.QRect(90, 186, 104, 31))
        self.set_id8.setObjectName("set_id8")
        self.set_id7 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id7.setGeometry(QtCore.QRect(90, 146, 104, 31))
        self.set_id7.setObjectName("set_id7")
        self.set_id6 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id6.setGeometry(QtCore.QRect(90, 106, 104, 31))
        self.set_id6.setObjectName("set_id6")
        self.set_id5 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id5.setGeometry(QtCore.QRect(90, 66, 104, 31))
        self.set_id5.setObjectName("set_id5")
        self.set_id4 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id4.setGeometry(QtCore.QRect(90, 26, 104, 31))
        self.set_id4.setObjectName("set_id4")
        self.set_id17 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id17.setGeometry(QtCore.QRect(90, 546, 104, 31))
        self.set_id17.setObjectName("set_id17")
        self.set_id20 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id20.setGeometry(QtCore.QRect(330, 106, 104, 31))
        self.set_id20.setObjectName("set_id20")
        self.set_id19 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id19.setGeometry(QtCore.QRect(330, 66, 104, 31))
        self.set_id19.setObjectName("set_id19")
        self.set_id18 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id18.setGeometry(QtCore.QRect(330, 26, 104, 31))
        self.set_id18.setObjectName("set_id18")
        self.set_id21 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id21.setGeometry(QtCore.QRect(330, 146, 104, 31))
        self.set_id21.setObjectName("set_id21")
        self.set_id22 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id22.setGeometry(QtCore.QRect(330, 186, 104, 31))
        self.set_id22.setObjectName("set_id22")
        self.set_id23 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id23.setGeometry(QtCore.QRect(330, 226, 104, 31))
        self.set_id23.setObjectName("set_id23")
        self.set_id24 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id24.setGeometry(QtCore.QRect(330, 266, 104, 31))
        self.set_id24.setObjectName("set_id24")
        self.set_id25 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id25.setGeometry(QtCore.QRect(330, 306, 104, 31))
        self.set_id25.setObjectName("set_id25")
        self.set_id26 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id26.setGeometry(QtCore.QRect(330, 352, 104, 31))
        self.set_id26.setObjectName("set_id26")
        self.set_id27 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id27.setGeometry(QtCore.QRect(330, 392, 104, 31))
        self.set_id27.setObjectName("set_id27")
        self.set_id28 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id28.setGeometry(QtCore.QRect(330, 432, 104, 31))
        self.set_id28.setObjectName("set_id28")
        self.radio_id13 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id13.setGeometry(QtCore.QRect(20, 390, 71, 23))
        self.radio_id13.setObjectName("radio_id13")
        self.radio_id14 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id14.setGeometry(QtCore.QRect(20, 430, 71, 23))
        self.radio_id14.setObjectName("radio_id14")
        self.radio_id15 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id15.setGeometry(QtCore.QRect(20, 470, 71, 23))
        self.radio_id15.setObjectName("radio_id15")
        self.radio_id16 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id16.setGeometry(QtCore.QRect(20, 510, 71, 23))
        self.radio_id16.setObjectName("radio_id16")
        self.radio_id17 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id17.setGeometry(QtCore.QRect(20, 550, 61, 23))
        self.radio_id17.setObjectName("radio_id17")
        self.radio_id18 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id18.setGeometry(QtCore.QRect(260, 30, 71, 23))
        self.radio_id18.setObjectName("radio_id18")
        self.radio_id19 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id19.setGeometry(QtCore.QRect(260, 70, 71, 23))
        self.radio_id19.setObjectName("radio_id19")
        self.radio_id20 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id20.setGeometry(QtCore.QRect(260, 111, 71, 23))
        self.radio_id20.setObjectName("radio_id20")
        self.radio_id21 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id21.setGeometry(QtCore.QRect(260, 150, 81, 23))
        self.radio_id21.setObjectName("radio_id21")
        self.radio_id24 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id24.setGeometry(QtCore.QRect(260, 266, 71, 23))
        self.radio_id24.setObjectName("radio_id24")
        self.radio_id22 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id22.setGeometry(QtCore.QRect(260, 189, 71, 23))
        self.radio_id22.setObjectName("radio_id22")
        self.radio_id23 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id23.setGeometry(QtCore.QRect(260, 230, 71, 23))
        self.radio_id23.setObjectName("radio_id23")
        self.radio_id25 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id25.setGeometry(QtCore.QRect(260, 310, 71, 23))
        self.radio_id25.setObjectName("radio_id25")
        self.radio_id26 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id26.setGeometry(QtCore.QRect(260, 356, 71, 23))
        self.radio_id26.setObjectName("radio_id26")
        self.radio_id27 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id27.setGeometry(QtCore.QRect(260, 397, 71, 23))
        self.radio_id27.setObjectName("radio_id27")
        self.radio_id28 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id28.setGeometry(QtCore.QRect(260, 436, 71, 23))
        self.radio_id28.setObjectName("radio_id28")
        self.set_id16 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id16.setGeometry(QtCore.QRect(90, 506, 104, 31))
        self.set_id16.setObjectName("set_id16")
        self.set_id10 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id10.setGeometry(QtCore.QRect(90, 266, 104, 31))
        self.set_id10.setObjectName("set_id10")
        self.set_id11 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id11.setGeometry(QtCore.QRect(90, 306, 104, 31))
        self.set_id11.setObjectName("set_id11")
        self.set_id12 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id12.setGeometry(QtCore.QRect(90, 346, 104, 31))
        self.set_id12.setObjectName("set_id12")
        self.set_id15 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id15.setGeometry(QtCore.QRect(90, 466, 104, 31))
        self.set_id15.setObjectName("set_id15")
        self.set_id14 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id14.setGeometry(QtCore.QRect(90, 426, 104, 31))
        self.set_id14.setObjectName("set_id14")
        self.set_id9 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id9.setGeometry(QtCore.QRect(90, 226, 104, 31))
        self.set_id9.setObjectName("set_id9")
        self.set_id13 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id13.setGeometry(QtCore.QRect(90, 386, 104, 31))
        self.set_id13.setObjectName("set_id13")
        self.radio_id29 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id29.setGeometry(QtCore.QRect(260, 474, 71, 23))
        self.radio_id29.setObjectName("radio_id29")
        self.radio_id30 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_id30.setGeometry(QtCore.QRect(260, 513, 71, 23))
        self.radio_id30.setObjectName("radio_id30")
        self.set_id29 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id29.setGeometry(QtCore.QRect(330, 470, 104, 31))
        self.set_id29.setObjectName("set_id29")
        self.set_id30 = QtWidgets.QTextEdit(self.groupBox)
        self.set_id30.setGeometry(QtCore.QRect(330, 510, 104, 31))
        self.set_id30.setObjectName("set_id30")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(670, 20, 471, 581))
        self.groupBox_2.setObjectName("groupBox_2")
        self.read_id28 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id28.setGeometry(QtCore.QRect(180, 430, 151, 21))
        self.read_id28.setObjectName("read_id28")
        self.read_id24 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id24.setGeometry(QtCore.QRect(180, 270, 161, 21))
        self.read_id24.setObjectName("read_id24")
        self.read_id13 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id13.setGeometry(QtCore.QRect(10, 390, 151, 21))
        self.read_id13.setObjectName("read_id13")
        self.read_id25 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id25.setGeometry(QtCore.QRect(180, 310, 161, 21))
        self.read_id25.setObjectName("read_id25")
        self.read_id14 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id14.setGeometry(QtCore.QRect(10, 430, 151, 21))
        self.read_id14.setObjectName("read_id14")
        self.read_id4 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id4.setGeometry(QtCore.QRect(10, 30, 151, 21))
        self.read_id4.setObjectName("read_id4")
        self.read_id23 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id23.setGeometry(QtCore.QRect(180, 230, 161, 21))
        self.read_id23.setObjectName("read_id23")
        self.read_id9 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id9.setGeometry(QtCore.QRect(10, 230, 151, 21))
        self.read_id9.setObjectName("read_id9")
        self.read_id20 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id20.setGeometry(QtCore.QRect(180, 110, 151, 21))
        self.read_id20.setObjectName("read_id20")
        self.read_id26 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id26.setGeometry(QtCore.QRect(180, 350, 161, 21))
        self.read_id26.setObjectName("read_id26")
        self.read_id17 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id17.setGeometry(QtCore.QRect(10, 550, 161, 21))
        self.read_id17.setObjectName("read_id17")
        self.read_id18 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id18.setGeometry(QtCore.QRect(180, 30, 161, 21))
        self.read_id18.setObjectName("read_id18")
        self.read_id5 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id5.setGeometry(QtCore.QRect(10, 70, 151, 21))
        self.read_id5.setObjectName("read_id5")
        self.read_id10 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id10.setGeometry(QtCore.QRect(10, 270, 151, 21))
        self.read_id10.setObjectName("read_id10")
        self.read_id21 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id21.setGeometry(QtCore.QRect(180, 150, 151, 21))
        self.read_id21.setObjectName("read_id21")
        self.read_id6 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id6.setGeometry(QtCore.QRect(10, 110, 151, 21))
        self.read_id6.setObjectName("read_id6")
        self.read_id7 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id7.setGeometry(QtCore.QRect(10, 150, 151, 21))
        self.read_id7.setObjectName("read_id7")
        self.read_id16 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id16.setGeometry(QtCore.QRect(10, 510, 151, 21))
        self.read_id16.setObjectName("read_id16")
        self.read_id27 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id27.setGeometry(QtCore.QRect(180, 390, 161, 21))
        self.read_id27.setObjectName("read_id27")
        self.read_id11 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id11.setGeometry(QtCore.QRect(10, 310, 151, 21))
        self.read_id11.setObjectName("read_id11")
        self.read_id15 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id15.setGeometry(QtCore.QRect(10, 470, 151, 21))
        self.read_id15.setObjectName("read_id15")
        self.read_id19 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id19.setGeometry(QtCore.QRect(180, 70, 151, 21))
        self.read_id19.setObjectName("read_id19")
        self.read_id8 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id8.setGeometry(QtCore.QRect(10, 190, 151, 21))
        self.read_id8.setObjectName("read_id8")
        self.read_id12 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id12.setGeometry(QtCore.QRect(10, 350, 151, 21))
        self.read_id12.setObjectName("read_id12")
        self.read_id22 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id22.setGeometry(QtCore.QRect(180, 190, 151, 21))
        self.read_id22.setObjectName("read_id22")
        self.read_id29 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id29.setGeometry(QtCore.QRect(180, 470, 151, 21))
        self.read_id29.setObjectName("read_id29")
        self.read_id30 = QtWidgets.QLabel(self.groupBox_2)
        self.read_id30.setGeometry(QtCore.QRect(180, 510, 151, 21))
        self.read_id30.setObjectName("read_id30")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(520, 10, 141, 591))
        self.groupBox_3.setObjectName("groupBox_3")
        self.cb_kakikiri = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_kakikiri.setGeometry(QtCore.QRect(10, 150, 121, 23))
        self.cb_kakikiri.setObjectName("cb_kakikiri")
        self.cb_badan = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_badan.setGeometry(QtCore.QRect(10, 30, 121, 23))
        self.cb_badan.setObjectName("cb_badan")
        self.cb_tangankiri = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_tangankiri.setGeometry(QtCore.QRect(10, 60, 121, 23))
        self.cb_tangankiri.setObjectName("cb_tangankiri")
        self.cb_kakikanan = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_kakikanan.setGeometry(QtCore.QRect(10, 120, 121, 23))
        self.cb_kakikanan.setObjectName("cb_kakikanan")
        self.cb_tangankanan = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_tangankanan.setGeometry(QtCore.QRect(10, 90, 121, 23))
        self.cb_tangankanan.setObjectName("cb_tangankanan")
        self.pb_onall = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_onall.setGeometry(QtCore.QRect(10, 180, 121, 25))
        self.pb_onall.setObjectName("pb_onall")
        self.pb_ofall = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_ofall.setGeometry(QtCore.QRect(10, 210, 121, 25))
        self.pb_ofall.setObjectName("pb_ofall")
        self.label_60 = QtWidgets.QLabel(self.groupBox_3)
        self.label_60.setGeometry(QtCore.QRect(20, 480, 101, 20))
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.pb_send = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_send.setGeometry(QtCore.QRect(20, 310, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(57)
        self.pb_send.setFont(font)
        self.pb_send.setObjectName("pb_send")
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setGeometry(QtCore.QRect(20, 490, 101, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.dial = QtWidgets.QDial(self.groupBox_3)
        self.dial.setGeometry(QtCore.QRect(20, 380, 101, 101))
        self.dial.setMaximum(359)
        self.dial.setObjectName("dial")
        self.pb_receive = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_receive.setGeometry(QtCore.QRect(20, 510, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(57)
        self.pb_receive.setFont(font)
        self.pb_receive.setObjectName("pb_receive")
        self.line1 = QtWidgets.QFrame(self.groupBox_3)
        self.line1.setGeometry(QtCore.QRect(20, 370, 101, 20))
        self.line1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setObjectName("line1")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(1150, 20, 311, 111))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox.setGeometry(QtCore.QRect(10, 50, 211, 25))
        self.comboBox.setObjectName("comboBox")
        self.pb_refresh = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_refresh.setGeometry(QtCore.QRect(230, 50, 71, 25))
        self.pb_refresh.setObjectName("pb_refresh")
        self.pb_connect = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_connect.setGeometry(QtCore.QRect(160, 80, 141, 25))
        self.pb_connect.setObjectName("pb_connect")
        self.lbl_status = QtWidgets.QLabel(self.groupBox_4)
        self.lbl_status.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.lbl_status.setObjectName("lbl_status")
        self.pb_disconnect = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_disconnect.setGeometry(QtCore.QRect(10, 80, 131, 25))
        self.pb_disconnect.setObjectName("pb_disconnect")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(1150, 130, 311, 261))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.LE_Step = QtWidgets.QLineEdit(self.groupBox_5)
        self.LE_Step.setGeometry(QtCore.QRect(10, 190, 191, 25))
        self.LE_Step.setText("")
        self.LE_Step.setObjectName("LE_Step")
        self.pb_export = QtWidgets.QPushButton(self.groupBox_5)
        self.pb_export.setGeometry(QtCore.QRect(110, 220, 89, 25))
        self.pb_export.setObjectName("pb_export")
        self.label_58 = QtWidgets.QLabel(self.groupBox_5)
        self.label_58.setGeometry(QtCore.QRect(160, 41, 67, 17))
        self.label_58.setObjectName("label_58")
        self.pb_load = QtWidgets.QPushButton(self.groupBox_5)
        self.pb_load.setGeometry(QtCore.QRect(10, 220, 89, 25))
        self.pb_load.setObjectName("pb_load")
        self.label_59 = QtWidgets.QLabel(self.groupBox_5)
        self.label_59.setGeometry(QtCore.QRect(10, 40, 41, 17))
        self.label_59.setObjectName("label_59")
        self.textEdit_TimeStep = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit_TimeStep.setGeometry(QtCore.QRect(50, 34, 104, 31))
        self.textEdit_TimeStep.setObjectName("textEdit_TimeStep")
        self.list_step = QtWidgets.QListWidget(self.groupBox_5)
        self.list_step.setGeometry(QtCore.QRect(10, 70, 291, 111))
        self.list_step.setObjectName("list_step")
        self.pb_import = QtWidgets.QPushButton(self.groupBox_5)
        self.pb_import.setGeometry(QtCore.QRect(210, 220, 89, 25))
        self.pb_import.setObjectName("pb_import")
        self.pb_save = QtWidgets.QPushButton(self.groupBox_5)
        self.pb_save.setGeometry(QtCore.QRect(210, 190, 89, 25))
        self.pb_save.setObjectName("pb_save")

        self.retranslateUi(Form)
        self.dial.valueChanged['int'].connect(self.label_60.setNum)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Set Position"))
        self.radio_id4.setText(_translate("Form", "ID[4]"))
        self.radio_id5.setText(_translate("Form", "ID[5]"))
        self.radio_id6.setText(_translate("Form", "ID[6]"))
        self.radio_id7.setText(_translate("Form", "ID[7]"))
        self.radio_id8.setText(_translate("Form", "ID[8]"))
        self.radio_id9.setText(_translate("Form", "ID[9]"))
        self.radio_id10.setText(_translate("Form", "ID[10]"))
        self.radio_id11.setText(_translate("Form", "ID[11]"))
        self.radio_id12.setText(_translate("Form", "ID[12]"))
        self.radio_id13.setText(_translate("Form", "ID[13]"))
        self.radio_id14.setText(_translate("Form", "ID[14]"))
        self.radio_id15.setText(_translate("Form", "ID[15]"))
        self.radio_id16.setText(_translate("Form", "ID[16]"))
        self.radio_id17.setText(_translate("Form", "ID[17]"))
        self.radio_id18.setText(_translate("Form", "ID[18]"))
        self.radio_id19.setText(_translate("Form", "ID[19]"))
        self.radio_id20.setText(_translate("Form", "ID[20]"))
        self.radio_id21.setText(_translate("Form", "ID[21]"))
        self.radio_id24.setText(_translate("Form", "ID[24]"))
        self.radio_id22.setText(_translate("Form", "ID[22]"))
        self.radio_id23.setText(_translate("Form", "ID[23]"))
        self.radio_id25.setText(_translate("Form", "ID[25]"))
        self.radio_id26.setText(_translate("Form", "ID[26]"))
        self.radio_id27.setText(_translate("Form", "ID[27]"))
        self.radio_id28.setText(_translate("Form", "ID[28]"))
        self.radio_id29.setText(_translate("Form", "ID[29]"))
        self.radio_id30.setText(_translate("Form", "ID[30]"))
        self.groupBox_2.setTitle(_translate("Form", "Read Position"))
        self.read_id28.setText(_translate("Form", "ID[28] : "))
        self.read_id24.setText(_translate("Form", "ID[24] : "))
        self.read_id13.setText(_translate("Form", "ID[13] : "))
        self.read_id25.setText(_translate("Form", "ID[25] : "))
        self.read_id14.setText(_translate("Form", "ID[14] : "))
        self.read_id4.setText(_translate("Form", "ID[4] : "))
        self.read_id23.setText(_translate("Form", "ID[23] : "))
        self.read_id9.setText(_translate("Form", "ID[9] : "))
        self.read_id20.setText(_translate("Form", "ID[20] : "))
        self.read_id26.setText(_translate("Form", "ID[26] : "))
        self.read_id17.setText(_translate("Form", "ID[17] : "))
        self.read_id18.setText(_translate("Form", "ID[18] : "))
        self.read_id5.setText(_translate("Form", "ID[5] : "))
        self.read_id10.setText(_translate("Form", "ID[10] : "))
        self.read_id21.setText(_translate("Form", "ID[21] : "))
        self.read_id6.setText(_translate("Form", "ID[6] : "))
        self.read_id7.setText(_translate("Form", "ID[7] : "))
        self.read_id16.setText(_translate("Form", "ID[16] : "))
        self.read_id27.setText(_translate("Form", "ID[27] : "))
        self.read_id11.setText(_translate("Form", "ID[11] : "))
        self.read_id15.setText(_translate("Form", "ID[15] :  "))
        self.read_id19.setText(_translate("Form", "ID[19] : "))
        self.read_id8.setText(_translate("Form", "ID[8] : "))
        self.read_id12.setText(_translate("Form", "ID[12] : "))
        self.read_id22.setText(_translate("Form", "ID[22] : "))
        self.read_id29.setText(_translate("Form", "ID[29] : "))
        self.read_id30.setText(_translate("Form", "ID[30] : "))
        self.groupBox_3.setTitle(_translate("Form", "Torsi"))
        self.cb_kakikiri.setText(_translate("Form", "Kaki Kiri"))
        self.cb_badan.setText(_translate("Form", "Badan"))
        self.cb_tangankiri.setText(_translate("Form", "Tangan Kiri"))
        self.cb_kakikanan.setText(_translate("Form", "Kaki Kanan"))
        self.cb_tangankanan.setText(_translate("Form", "Tangan Kanan"))
        self.pb_onall.setText(_translate("Form", "On - All"))
        self.pb_ofall.setText(_translate("Form", "Off - All"))
        self.label_60.setText(_translate("Form", "0"))
        self.pb_send.setText(_translate("Form", "→"))
        self.pb_receive.setText(_translate("Form", "←"))
        self.pb_refresh.setText(_translate("Form", "REFRESH"))
        self.pb_connect.setText(_translate("Form", "CONNECT"))
        self.lbl_status.setText(_translate("Form", "Status : Disconnect"))
        self.pb_disconnect.setText(_translate("Form", "DISCONNECT"))
        self.pb_export.setText(_translate("Form", "EXPORT"))
        self.label_58.setText(_translate("Form", "ms"))
        self.pb_load.setText(_translate("Form", "LOAD"))
        self.label_59.setText(_translate("Form", "Time"))
        self.textEdit_TimeStep.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.pb_import.setText(_translate("Form", "IMPORT"))
        self.pb_save.setText(_translate("Form", "SAVE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
